// GENERATED by scripts/extract-commands.mjs from the server's own Server.jar.
// Do not edit by hand: re-run the extractor against the new jar instead.
//
// The single source of truth for which commands exist, what they take, and
// which of them this daemon will send - in the same spirit as
// LAUNCH_OPTION_FIELDS. Extracted rather than transcribed from the wiki
// because the game declares its parameters with types and optionality and the
// wiki does not.
//
// stop, exit and quit are absent on purpose. The daemon owns the server's
// lifecycle and its stop never escalates to a kill, so a second path to
// stopping it is a race, not a feature. Absence is the enforcement: a name
// that is not here cannot be composed.
import type { CommandDef } from "./types.js";

/** The game version this table was taken from. Compared against the running server. */
export const SCHEMA_GAME_VERSION = "1.3.1";

export const SERVER_COMMANDS: readonly CommandDef[] = [
  {
    name: "allowcheats",
    description: "Enables/allows cheats on this world (NOT REVERSIBLE)",
    permission: "OWNER",
    isCheat: true,
    destructive: true,
    params: [],
  },
  {
    name: "armorset",
    description: "Gives full armor set to player",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "player", type: "player", optional: true },
      { name: "setname", type: "text", optional: false },
    ],
  },
  {
    name: "ban",
    description: "Bans a player",
    permission: "ADMIN",
    isCheat: false,
    params: [
      { name: "authentication/name", type: "text", optional: false },
    ],
  },
  {
    name: "bans",
    description: "Lists all current bans",
    permission: "ADMIN",
    isCheat: false,
    params: [],
  },
  {
    name: "buff",
    description: "Gives buff to player",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "player", type: "player", optional: true },
      { name: "buff", type: "text", optional: false },
      { name: "seconds", type: "float", optional: true },
    ],
  },
  {
    name: "calculatevalue",
    description: "Calculates the broker value of an item based on recipes",
    permission: "USER",
    isCheat: false,
    params: [
      { name: "item", type: "text", optional: false },
    ],
  },
  {
    name: "changename",
    description: "Changes the name of a player",
    permission: "ADMIN",
    isCheat: false,
    params: [
      { name: "player", type: "player", optional: false },
      { name: "name", type: "text", optional: false },
    ],
  },
  {
    name: "clearall",
    description: "Clears all entities",
    permission: "ADMIN",
    isCheat: true,
    destructive: true,
    params: [
      { name: "global", type: "bool", optional: true },
    ],
  },
  {
    name: "cleararea",
    description: "Clears an area around the player",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "player", type: "player", optional: true },
      { name: "radius", type: "int", optional: true },
      { name: "tile", type: "text", optional: true },
    ],
  },
  {
    name: "clearbuff",
    description: "Clears buff from player",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "player", type: "player", optional: true },
      { name: "buff", type: "text", optional: false },
    ],
  },
  {
    name: "clearconnection",
    description: "Clears the connection info of a client, making them try to reconnect to session",
    permission: "OWNER",
    isCheat: true,
    params: [
      { name: "player", type: "player", optional: false },
    ],
  },
  {
    name: "cleardrops",
    description: "Clears all drops or a specific type on your level or on all loaded levels",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "global", type: "bool", optional: true },
      { name: "type", type: "text", optional: true },
    ],
  },
  {
    name: "clearevents",
    description: "Clears all events on your level or on all loaded levels",
    permission: "ADMIN",
    isCheat: true,
    destructive: true,
    params: [
      { name: "global", type: "bool", optional: true },
      { name: "type", type: "text", optional: true },
    ],
  },
  {
    name: "clearmobs",
    description: "Clears all mobs or a specific type on your level or on all loaded levels",
    permission: "ADMIN",
    isCheat: true,
    destructive: true,
    params: [
      { name: "global", type: "bool", optional: true },
      { name: "type", type: "text", optional: true },
    ],
  },
  {
    name: "clearteam",
    description: "Removes the player from his current team",
    permission: "ADMIN",
    isCheat: false,
    params: [
      { name: "player", type: "text", optional: false },
    ],
  },
  {
    name: "clientloadingperformance",
    description: "Record and print the debug loading performance timer over a period on current level",
    permission: "USER",
    isCheat: false,
    params: [
      { name: "intervalSeconds", type: "int", optional: false },
      { name: "maxPrints", type: "int", optional: true },
    ],
  },
  {
    name: "completeincursion",
    description: "Force completes an incursion objective. Use multiple times to fully complete",
    permission: "OWNER",
    isCheat: true,
    params: [
      { name: "level", type: "text", optional: true },
    ],
  },
  {
    name: "copyitem",
    description: "Copies an item and all of its data",
    permission: "ADMIN",
    isCheat: true,
    playerOnly: true,
    params: [
      { name: "slot", type: "int", optional: true },
    ],
  },
  {
    name: "copyplayer",
    description: "Copy a players inventory, position and health over to another",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "from", type: "player", optional: false },
      { name: "to", type: "player", optional: false },
    ],
  },
  {
    name: "createteam",
    description: "Creates a new team for yourself",
    permission: "USER",
    isCheat: false,
    playerOnly: true,
    params: [],
  },
  {
    name: "creativemode",
    description: "Enables creative mode (not reversible). Will disabled achievements.",
    permission: "OWNER",
    isCheat: false,
    params: [],
  },
  {
    name: "deathpenalty",
    description: "Changes death penalty setting",
    permission: "ADMIN",
    isCheat: false,
    params: [
      { name: "list/penalty", type: "text", optional: false },
    ],
  },
  {
    name: "deletelevel",
    description: "Deletes a level if possible and teleports players back to their fallback level",
    permission: "OWNER",
    isCheat: true,
    params: [
      { name: "level", type: "text", optional: true },
    ],
  },
  {
    name: "deleteplayer",
    description: "Deletes a players files in the saved players folder",
    permission: "ADMIN",
    isCheat: false,
    destructive: true,
    params: [
      { name: "authentication/fullname", type: "text", optional: false },
    ],
  },
  {
    name: "die",
    description: "Kills yourself",
    permission: "USER",
    isCheat: false,
    playerOnly: true,
    params: [],
  },
  {
    name: "difficulty",
    description: "Changes difficulty setting",
    permission: "ADMIN",
    isCheat: false,
    params: [
      { name: "list/difficulty", type: "text", optional: false },
    ],
  },
  {
    name: "enchant",
    description: "Clears, sets or gives a random enchant (use -1 slot for selected item)",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "clear/set/random", type: "enum", optional: false, values: ["clear", "set", "random"] },
      { name: "slot", type: "int", optional: true },
      { name: "enchantID", type: "text", optional: true },
    ],
  },
  {
    name: "endraid",
    description: "Ends a raid at the players current location",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "player", type: "player", optional: true },
    ],
  },
  {
    name: "getteam",
    description: "Gets the current team of the player",
    permission: "ADMIN",
    isCheat: false,
    params: [
      { name: "player", type: "text", optional: false },
    ],
  },
  {
    name: "give",
    description: "Gives item to player",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "player", type: "player", optional: true },
      { name: "item", type: "text", optional: false },
      { name: "amount", type: "int", optional: true },
    ],
  },
  {
    name: "healmobs",
    description: "Heals mobs around you",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "health", type: "int", optional: false },
      { name: "range", type: "int", optional: true },
      { name: "filter", type: "text", optional: true },
    ],
  },
  {
    name: "help",
    description: "Lists all commands or gives information about a specific command",
    permission: "USER",
    isCheat: false,
    params: [
      { name: "page/command", type: "text", optional: true },
    ],
  },
  {
    name: "hp",
    description: "Sets the health of player",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "player", type: "player", optional: true },
      { name: "health", type: "int", optional: false },
    ],
  },
  {
    name: "hunger",
    description: "Sets the hunger percent of player",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "player", type: "player", optional: true },
      { name: "hunger", type: "float", optional: false },
    ],
  },
  {
    name: "invincibility",
    description: "Sets a players invincibility",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "player", type: "player", optional: true },
      { name: "1/0", type: "bool", optional: true },
    ],
  },
  {
    name: "invite",
    description: "Invites a player to your team",
    permission: "USER",
    isCheat: false,
    playerOnly: true,
    params: [
      { name: "player", type: "player", optional: false },
    ],
  },
  {
    name: "itemgnd",
    description: "Gets or sets item GND data",
    permission: "OWNER",
    isCheat: true,
    params: [
      { name: "slot", type: "int", optional: true },
      { name: "set/get/clear", type: "enum", optional: false, values: ["set", "get", "clear"] },
      { name: "key", type: "text", optional: true },
      { name: "value", type: "text", optional: true },
    ],
  },
  {
    name: "kick",
    description: "Kicks player from the server",
    permission: "MODERATOR",
    isCheat: false,
    params: [
      { name: "player", type: "player", optional: false },
      { name: "message/reason", type: "text", optional: true },
    ],
  },
  {
    name: "language",
    description: "Sets server language settings",
    permission: "SERVER",
    isCheat: false,
    params: [
      { name: "language", type: "text", optional: false },
    ],
  },
  {
    name: "leaveteam",
    description: "Leaves your current team",
    permission: "USER",
    isCheat: false,
    playerOnly: true,
    params: [],
  },
  {
    name: "levels",
    description: "Lists currently loaded levels",
    permission: "MODERATOR",
    isCheat: false,
    params: [],
  },
  {
    name: "mana",
    description: "Sets the mana of player",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "player", type: "player", optional: true },
      { name: "mana", type: "int", optional: false },
    ],
  },
  {
    name: "maxhp",
    description: "Sets the max health of player",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "player", type: "player", optional: true },
      { name: "health", type: "int", optional: false },
      { name: "ignoreHealthUpgrades", type: "bool", optional: true },
    ],
  },
  {
    name: "maxlatency",
    description: "Sets the max latency before client timeout",
    permission: "ADMIN",
    isCheat: false,
    params: [
      { name: "seconds", type: "int", optional: false },
    ],
  },
  {
    name: "maxmana",
    description: "Sets the max mana of player",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "player", type: "player", optional: true },
      { name: "mana", type: "int", optional: false },
    ],
  },
  {
    name: "me",
    description: "Declare an action to the entire server",
    permission: "USER",
    isCheat: false,
    playerOnly: true,
    params: [
      { name: "action", type: "text", optional: false },
    ],
  },
  {
    name: "motd",
    description: "Sets or clears the message of the day. Use \\n for new line",
    permission: "ADMIN",
    isCheat: false,
    params: [
      { name: "clear/get/message", type: "text", optional: false },
    ],
  },
  {
    name: "mow",
    description: "Mows ground of grass in range with percent chance",
    permission: "ADMIN",
    isCheat: true,
    playerOnly: true,
    params: [
      { name: "range", type: "int", optional: false },
      { name: "chance", type: "float", optional: true },
    ],
  },
  {
    name: "mypermissions",
    description: "Shows your permission level",
    permission: "USER",
    isCheat: false,
    playerOnly: true,
    params: [],
  },
  {
    name: "network",
    description: "Shows network usage this session",
    permission: "MODERATOR",
    isCheat: false,
    playerOnly: true,
    params: [],
  },
  {
    name: "openhelpform",
    description: "Opens a predefined help form",
    permission: "USER",
    isCheat: false,
    params: [
      { name: "form", type: "text", optional: false },
    ],
  },
  {
    name: "password",
    description: "Set a password of the server, blank will be no password",
    permission: "OWNER",
    isCheat: false,
    params: [
      { name: "password", type: "text", optional: true },
    ],
  },
  {
    name: "pausewhenempty",
    description: "Enable/disable pause when empty setting",
    permission: "ADMIN",
    isCheat: false,
    params: [
      { name: "0/1", type: "bool", optional: false },
    ],
  },
  {
    name: "performance",
    description: "Records server performance over some seconds and creates a file with the results",
    permission: "USER",
    isCheat: false,
    playerOnly: true,
    params: [
      { name: "includeServer", type: "bool", optional: true },
      { name: "seconds", type: "int", optional: true },
    ],
  },
  {
    name: "permissions",
    description: "Sets a players permissions",
    permission: "OWNER",
    isCheat: false,
    params: [
      { name: "list/set/get", type: "enum", optional: false, values: ["list", "set", "get"] },
      { name: "authentication/name", type: "player", optional: true },
      { name: "permissions", type: "text", optional: true },
    ],
  },
  {
    name: "playernames",
    description: "Lists all authentications and their names",
    permission: "MODERATOR",
    isCheat: false,
    params: [],
  },
  {
    name: "players",
    description: "Lists players currently online",
    permission: "MODERATOR",
    isCheat: false,
    params: [],
  },
  {
    name: "playtime",
    description: "Shows your current playtime on the server",
    permission: "USER",
    isCheat: false,
    playerOnly: true,
    params: [],
  },
  {
    name: "pm",
    description: "Whisper a message to another player",
    permission: "USER",
    isCheat: false,
    params: [
      { name: "player", type: "player", optional: false },
      { name: "message", type: "text", optional: false },
    ],
  },
  {
    name: "print",
    description: "Prints a message in the chat",
    permission: "ADMIN",
    isCheat: false,
    params: [
      { name: "message", type: "text", optional: false },
    ],
  },
  {
    name: "raids",
    description: "Changes raids frequency setting",
    permission: "ADMIN",
    isCheat: false,
    params: [
      { name: "list/frequency", type: "text", optional: false },
    ],
  },
  {
    name: "rain",
    description: "Sets the rain on the level",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "islandX", type: "int", optional: true },
      { name: "islandY", type: "int", optional: true },
      { name: "dimension", type: "int", optional: true },
      { name: "start/clear", type: "enum", optional: false, values: ["start", "clear"] },
    ],
  },
  {
    name: "regen",
    description: "Regenerates the entire level",
    permission: "OWNER",
    isCheat: true,
    destructive: true,
    params: [
      { name: "seeded", type: "bool", optional: true },
      { name: "level", type: "text", optional: true },
    ],
  },
  {
    name: "resetcharacterromance",
    description: "Resets all relationships/dating progress for the given client",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "global", type: "bool", optional: true },
      { name: "player", type: "player", optional: true },
    ],
  },
  {
    name: "resethealthupgrades",
    description: "Resets the health upgrades of a player",
    permission: "OWNER",
    isCheat: true,
    params: [
      { name: "player", type: "player", optional: true },
    ],
  },
  {
    name: "resilience",
    description: "Sets the resilience of player",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "player", type: "player", optional: true },
      { name: "resilience", type: "int", optional: false },
    ],
  },
  {
    name: "save",
    description: "Saves all data",
    permission: "MODERATOR",
    isCheat: false,
    params: [
      { name: "recordPerformance", type: "bool", optional: true },
    ],
  },
  {
    name: "say",
    description: "Talks in the chat as Server",
    permission: "MODERATOR",
    isCheat: false,
    params: [
      { name: "message", type: "text", optional: false },
    ],
  },
  {
    name: "serverloadingperformance",
    description: "Record and print the debug loading performance timer over a period on current level",
    permission: "USER",
    isCheat: false,
    params: [
      { name: "intervalSeconds", type: "int", optional: false },
      { name: "maxPrints", type: "int", optional: true },
    ],
  },
  {
    name: "setdimension",
    description: "Changes the dimension of player",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "player", type: "player", optional: true },
      { name: "dimension", type: "text", optional: false },
    ],
  },
  {
    name: "setisland",
    description: "Changes the island of the player",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "player", type: "player", optional: true },
      { name: "islandX", type: "text", optional: false },
      { name: "islandY", type: "text", optional: false },
      { name: "dimension", type: "text", optional: true },
    ],
  },
  {
    name: "setlevel",
    description: "Changes the level of the player",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "player", type: "player", optional: true },
      { name: "level", type: "text", optional: false },
    ],
  },
  {
    name: "setposition",
    description: "Changes the position of the player",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "player", type: "player", optional: true },
      { name: "level", type: "text", optional: true },
      { name: "tileX", type: "text", optional: false },
      { name: "tileY", type: "text", optional: false },
      { name: "ignoreUnknownLevels", type: "bool", optional: true },
    ],
  },
  {
    name: "setraiddifficulty",
    description: "Set the next raid difficulty of the settlement at players current location",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "player", type: "player", optional: true },
      { name: "percent", type: "int", optional: false },
    ],
  },
  {
    name: "setromancelevelforclosestsettler",
    description: "Finds a nearby settler and sets their romance level to your param",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "romanceLevel", type: "int", optional: false },
    ],
  },
  {
    name: "setteam",
    description: "Sets the team of the player.",
    permission: "ADMIN",
    isCheat: false,
    params: [
      { name: "player", type: "text", optional: false },
      { name: "team", type: "text", optional: false },
    ],
  },
  {
    name: "setteamowner",
    description: "Sets the owner of the team. The new owner must be part of the team already",
    permission: "ADMIN",
    isCheat: false,
    params: [
      { name: "team", type: "text", optional: false },
      { name: "player", type: "text", optional: false },
    ],
  },
  {
    name: "settings",
    description: "Change server world settings",
    permission: "ADMIN",
    isCheat: false,
    params: [
      { name: "list/setting", type: "enum", optional: false, values: ["list"] },
      { name: "arg", type: "text", optional: true },
    ],
  },
  {
    name: "settlements",
    description: "Lists found settlements",
    permission: "MODERATOR",
    isCheat: false,
    params: [
      { name: "onlyLoaded", type: "bool", optional: true },
    ],
  },
  {
    name: "spawnsettler",
    description: "Spawns a settler on the level",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "tileX", type: "int", optional: true },
      { name: "tileY", type: "int", optional: true },
      { name: "level", type: "text", optional: true },
      { name: "settler", type: "text", optional: false },
      { name: "recruited", type: "bool", optional: true },
    ],
  },
  {
    name: "spawnvisitor",
    description: "Spawns a settlement visitor on the level",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "tileX", type: "int", optional: true },
      { name: "tileY", type: "int", optional: true },
      { name: "level", type: "text", optional: true },
      { name: "visitor", type: "text", optional: true },
    ],
  },
  {
    name: "startraid",
    description: "Starts a raid at the players current location",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "player", type: "player", optional: true },
      { name: "direction", type: "text", optional: true },
      { name: "dontAttack", type: "bool", optional: true },
    ],
  },
  {
    name: "startraidattack",
    description: "Triggers a raid to attack at the players current location",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "player", type: "player", optional: true },
    ],
  },
  {
    name: "staticdamage",
    description: "Makes all damage not be randomized",
    permission: "OWNER",
    isCheat: true,
    params: [
      { name: "value", type: "bool", optional: false },
    ],
  },
  {
    name: "stophelp",
    description: "Saves and stops the server",
    permission: "OWNER",
    isCheat: false,
    params: [],
  },
  {
    name: "time",
    description: "Sets/adds world time (can use (mid)day or (mid)night)",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "set/add", type: "enum", optional: false, values: ["set", "add", "day", "dawn", "morning", "noon", "midday", "dusk", "night", "midnight"] },
      { name: "amount", type: "int", optional: true },
    ],
  },
  {
    name: "tp",
    description: "Teleports player1 to player2 or other location",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "player1", type: "player", optional: true },
      { name: "player2/home/death/spawn/level", type: "text", optional: false },
    ],
  },
  {
    name: "unban",
    description: "Removes a ban",
    permission: "ADMIN",
    isCheat: false,
    params: [
      { name: "authentication/name", type: "text", optional: false },
    ],
  },
  {
    name: "upgrade",
    description: "Clears or sets the tier on an item (use -1 slot for selected item)",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "slot", type: "int", optional: true },
      { name: "tier", type: "int", optional: false },
    ],
  },
  {
    name: "upgradeall",
    description: "Clears or sets the tier on all items equipped and on your hotbar",
    permission: "ADMIN",
    isCheat: true,
    params: [
      { name: "tier", type: "int", optional: false },
    ],
  },
  {
    name: "w",
    description: "Whisper a message to another player",
    permission: "USER",
    isCheat: false,
    params: [
      { name: "player", type: "player", optional: false },
      { name: "message", type: "text", optional: false },
    ],
  },
  {
    name: "whisper",
    description: "Whisper a message to another player",
    permission: "USER",
    isCheat: false,
    params: [
      { name: "player", type: "player", optional: false },
      { name: "message", type: "text", optional: false },
    ],
  },
  {
    name: "whisperhelp",
    description: "Whisper a message to another player",
    permission: "USER",
    isCheat: false,
    params: [
      { name: "player", type: "player", optional: false },
      { name: "message", type: "text", optional: false },
    ],
  },
  {
    name: "worldseed",
    description: "Prints the world seed",
    permission: "OWNER",
    isCheat: false,
    params: [],
  },
];
